name: Delphi package

on: [push, pull_request]

jobs:
  build_sempare_template_engine:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: build win32 debug
        id: build_win32_debug
        run: |
          "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"
          msbuild Sempare.Template.Tester.dproj /t:Build /p:Config=Debug /p:Platform=Win32
        run: scripts\build.bat debug


      - name: build win32 release
        id: build_win32_release
        run: |
          "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"
          msbuild Sempare.Template.Tester.dproj /t:Build /p:Config=Release /p:Platform=Win32
        run: scripts\build.bat release

