name: Delphi package

on: [push, pull_request]

jobs:
  build_sempare_template_engine:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: build win32 debug
        shell: cmd
        id: build_win32_debug
        run: |
          call "scripts\bootstrap.bat" Debug Win32

      - name: build win32 release
        id: build_win32_release
        shell: cmd
        run: |
          call "scripts\bootstrap.bat" Release Win32

