name: Delphi package

on: [push, pull_request]

jobs:
  build_sempare_template_engine:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    env:
       MSBUILD_PATH: C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild
       PATH: %PATH%;MSBUILD_PATH
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: build win32 debug
        shell: cmd
        id: build_win32_debug
        run: |
          scripts/build.bat debug
      - name: build win32 release
        shell: cmd
        id: build_win32_release
        run: |
          scripts/build.bat release
