name: Delphi package

on: [push]

jobs:
  build_sempare_template_engine:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Remove comment from specific line in file
        run: |
          $filePath = "src/Sempare.Template.Compiler.inc"
          $lineToFind = '// {$DEFINE SEMPARE_TEMPLATE_CONFIRM_LICENSE}'
          $newLine = '{$DEFINE SEMPARE_TEMPLATE_CONFIRM_LICENSE}'
          (Get-Content $filePath) -replace [regex]::Escape($lineToFind), $newLine | Set-Content $filePath
      
      - name: build win32 debug
        shell: cmd
        id: build_win32_debug
        working-directory: scripts
        run: bootstrap.bat Debug Win32

      - name: run win32 debug tests
        shell: cmd
        id: run_win32_debug_tests
        working-directory: Win32\Debug
        run: Sempare.Template.Tester.exe -cm:quiet -exit:continue -b -xmlfile:.\test-results.xml

      - name: Generate Test Report
        run: reportgenerator -reports:./test-results.xml -targetdir:TestReport -reporttypes:HtmlInline_AzurePipelines


      - name: build win32 release
        id: build_win32_release
        working-directory: scripts
        shell: cmd
        run: bootstrap.bat Release Win32

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: TestReport
          path: TestReport

      - name: run win64 release tests
        shell: cmd
        id: run_win32_release_tests
        working-directory: Win32\Release
        run: Sempare.Template.Tester.exe -cm:quiet -exit:continue -b -xmlfile:.\test-results.xml

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: 'Win32\Debug\test-results.xml'

