name: Delphi package

on: [push]

jobs:
  build_sempare_template_engine:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Remove comment from specific line in file
        run: |
          $filePath = "src/Sempare.Template.Compiler.inc"
          $lineToFind = '// {$DEFINE SEMPARE_TEMPLATE_CONFIRM_LICENSE}'
          $newLine = '{$DEFINE SEMPARE_TEMPLATE_CONFIRM_LICENSE}'
          (Get-Content $filePath) -replace [regex]::Escape($lineToFind), $newLine | Set-Content $filePath
      
      - name: build win32 debug
        shell: cmd
        id: build_win32_debug
        working-directory: scripts
        run: bootstrap.bat Debug Win32

      - name: run win32 debug tests
        shell: cmd
        working-directory: Win32\Debug
        run: Sempare.Template.Tester.exe -cm:quiet -exit:continue -b -xmlfile:..\..\test-results.xml

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: './test-results.xml'

      - name: Report Test Results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: './test-results.xml'
          require_tests: true

