name: Delphi package

on: [push]

jobs:
  build_sempare_template_engine:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: remove comment from specific line in file
        run: |
          $filePath = "src/Sempare.Template.Compiler.inc"
          $lineToFind = '// {$DEFINE SEMPARE_TEMPLATE_CONFIRM_LICENSE}'
          $newLine = '{$DEFINE SEMPARE_TEMPLATE_CONFIRM_LICENSE}'
          (Get-Content $filePath) -replace [regex]::Escape($lineToFind), $newLine | Set-Content $filePath
      
      - name: build win32 debug
        shell: cmd
        working-directory: scripts
        run: build.bat Debug Win32

      - name: run win32 debug tests
        shell: cmd
        working-directory: Win32\Debug
        run: Sempare.Template.Tester.exe -cm:quiet -exit:continue -b -xmlfile:./test-results.xml

      - name: publish win32 debug test results
        uses: actions/upload-artifact@v2
        with:
          name: Win32 Debug Results
          path: './Win32/Debug/test-results.xml'

      - name: publish win32 debug test results
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: Win32 Debug Results
          report_paths: './Win32/Debug/test-results.xml'


      - name: build win32 release
        shell: cmd
        working-directory: scripts
        run: build.bat Release Win32

      - name: run win32 release tests
        shell: cmd
        working-directory: Win32\Release
        run: Sempare.Template.Tester.exe -cm:quiet -exit:continue -b -xmlfile:./test-results-release.xml

      - name: publish win32 release test results
        uses: actions/upload-artifact@v2
        with:
          name: Win32 Release Results
          path: './Win32/Release/test-results-release.xml'

      - name: publish win32 release test results
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: Win32 Release Results
          report_paths: './Win32/Release/test-results-release.xml'

